//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef CIRCT_DIALECT_PEXCS_PEXCS_TD
#define CIRCT_DIALECT_PEXCS_PEXCS_TD

include "circt/Dialect/Pexcs/PexcsDialect.td"
include "circt/Dialect/Pexcs/PexcsOps.td"
include "circt/Dialect/Pexcs/PexcsTypes.td"

#endif // CIRCT_DIALECT_PEXCS_PEXCS_TD 